name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Clean and install dependencies
      run: |
        echo "Cleaning previous installations..."
        rm -rf node_modules package-lock.json
        echo "Installing dependencies..."
        npm install --include=optional --no-audit --no-fund
        echo "Dependencies installed successfully"

    - name: Build application
      run: |
        echo "Building application..."
        npm run build
        echo "Build completed"

    - name: Verify build output
      run: |
        echo "Verifying build output..."
        ls -la dist/
        ls -la dist/public/
        if [ ! -f "dist/index.js" ]; then
          echo "❌ Backend build failed: dist/index.js not found"
          exit 1
        fi
        if [ ! -d "dist/public" ]; then
          echo "❌ Frontend build failed: dist/public directory not found"
          exit 1
        fi
        echo "✅ Build verification successful"

    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        
        # Copy necessary files for deployment
        cp package.json dist/
        cp web.config dist/
        cp startup.sh dist/
        chmod +x dist/startup.sh
        
        # Copy production dependencies
        cp -r node_modules dist/
        
        # Verify the deployment package
        echo "Checking dist contents:"
        ls -la dist/
        echo "Checking if index.js exists:"
        ls -la dist/index.js
        echo "Checking if public folder exists:"
        ls -la dist/public/
        
        echo "Deployment package created"

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./dist
        clean: true 